image: docker:latest

services:
  - docker:18.09.6-dind

stages:
  - test
  - build
  - package
  - deploy

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://localhost:2375"
  REPOSITORY_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_PIPELINE_IID}"

cache:
  paths:
    - node_modules/

tests:
  tags:
    - kuber
  stage: test
  only:
    - master
  image: node:12.10-alpine
  script:
  - apk --no-cache add --virtual native-deps g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python git 
  - npm install
  - NODE_ENV=test npm run test

build:
  tags:
    - kuber
  stage: build
  only:
    - master
  image: node:12.10-alpine
  script:
  - apk --no-cache add --virtual native-deps g++ gcc libgcc libstdc++ linux-headers autoconf automake make nasm python git
  - npm install
  - npm run build
  artifacts:
    paths:
    - dist

package:
  tags:
    - kuber
  stage: package
  only:
    - master
  image: docker:18.09.6-dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN ${CI_REGISTRY}
  - docker build -t ${REPOSITORY_IMAGE} .
  - docker push ${REPOSITORY_IMAGE}

deploy:
  tags:
  - kuber
  stage: deploy
  only:
  - master
  image: roffe/kubectl:v1.13.2
  script:
  - NAMESPACE_NAME=$(echo -e gitdep-$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME | tr -d _)
  - CI_PROJECT_NAME=$(echo -e $CI_PROJECT_NAME | tr -d _)
  - HOSTNAME=$(echo -e $CI_PROJECT_PATH | tr '/' '-' | tr '_' '-')
  - sed -i -e "s@__NAMESPACE_NAME__@${NAMESPACE_NAME}@g" dp.yml
  - sed -i -e "s@__CI_PROJECT_NAME__@${CI_PROJECT_NAME}@g" dp.yml
  - sed -i -e "s@__REPOSITORY_IMAGE__@${REPOSITORY_IMAGE}@g" dp.yml
  - sed -i -e "s@__HOSTNAME__@${HOSTNAME}@g" dp.yml
  - kubectl config set-cluster test-cluster --server=$(kubectl describe services | grep IP | sed -E 's/IP:[[:space:]]+//' | sed -E 's/Type:[[:space:]]+//' | tr -d ClusterIP)
  - kubectl create secret -n "$NAMESPACE_NAME" docker-registry gitlab-registry --docker-server="$CI_REGISTRY" --docker-username="$REGISTRY_DEPLOY_LOGIN" --docker-password="$REGISTRY_DEPLOY_TOKEN" --docker-email="$GITLAB_USER_EMAIL" -o yaml --dry-run | kubectl replace -n "$NAMESPACE_NAME" --force -f -
  - kubectl apply -f dp.yml
