image: docker:latest
services:
  - docker:18.09.6-dind

stages:
  - analysis

variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: "tcp://localhost:2375"

project-analysis-code:
  stage: analysis
  image: ciricihq/gitlab-sonar-scanner:3.2.1
  variables:
    SONAR_URL: http://sonarqube-sonarqube.sonarqube:9000
    SONAR_ANALYSIS_MODE: publish
  only:
  - master
  script:
  - gitlab-sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.url=https://gitlab.onix.ua/
  tags:
  - kuber
